logging:
  level:
    #ROOT: DEBUG
    org.springframework.web: ERROR
    de.gishmo.gwtbootstartermvp4g2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/mkyong/debug.log